[package]
name = "gimei"
version = "0.1.1"
authors = [ "woxtu <woxtup@gmail.com>" ]
license = "MIT"
description = "Generate fake name for Japanese"

[dependencies]
lazy_static = "1.0"
rand = "0.5"
yaml-rust = "0.4"

[dev-dependencies]
regex = "1.0"

[[test]]
name = "test"
path = "test/test.rs"
